#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <testkit.h>

// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define MAX_LENGTH 8192
#define TOP_N 5

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

void addSyscall(syscall_stats *stats, const char *name, double time) { 
    for(int i = 0; i < stats->count; ++i) {
        if(strcmp(stats->stats[i].name, name) == 0) {
            stats->stats[i].time += time;
            return ;
        }
    }
    strcpy(stats->stats[stats->count].name, name);
    stats->stats[stats->count].time = time;
    ++stats->count;
}

void print_top_syscalls(syscall_stats *stats, int n) {

}

void getSyscallName(const char* line, int length, char* name) {
    int name_idx = 0;
    while(name_idx < length && ((line[name_idx] >= 'a' && line[name_idx] <= 'z') ||
          (line[name_idx] >= 'A' && line[name_idx] <= 'Z'))) {
        name[name_idx] = line[name_idx];
        ++name_idx;
    }
}
UnitTest(testGetSyscallName) {
    char line[MAX_LENGTH] = "TestSyscall: test test <1.2>";
    int len = strlen(line);
    char name[MAX_LENGTH];
    getSyscallName(line, len, name);
    assert(strcmp(name, "TestSyscall") == 0);
}

double getSyscallTime(const char* line, int length) {
    int idx = 0;
    double time = 0.0;
    while(idx < length && line[idx] != '<') {
        ++idx;
    }
    ++idx;
    while(idx < length && line[idx] != '.') {
        if(line[idx] >= '0' && line[idx] <= '9') {
            time = time * 10 + (line[idx] - '0');
        }
        else {
            perror("Error: get syscall time failed.\n");
            exit(1);
        }
        ++idx;
    }
    ++idx;
    double base = 0.1;
    while(idx < length && line[idx] != '>') {
        if(line[idx] >= '0' && line[idx] <= '9') {
            time += base * (line[idx] - '0');
        }
        else {
            perror("Error: get syscall time failed.\n");
            exit(1);
        }
        base *= 0.1;
        ++idx;
    }
    return time;
}
UnitTest(testGetSyscallTime) {
    char line[20] = "tests <123.1234>";
    int length = strlen(line);
    double eps = 0.0001;
    double time = 0.0;
    time = getSyscallTime(line, length);
    printf("%lf\n", time);
    assert((time - 123.1234) < eps && (time - 123.1234) > -eps);
}
int main(int argc, char *argv[]) {
    if(argc == 1) {
        perror("Error: missing command to trace.\n");
        return 1;
    }
    int fd[2];
    pipe(fd);

    int pid = fork();

    if(pid == 0) { // child process
        int origin_stderr = dup(STDERR_FILENO);
        printf("%d\n", origin_stderr);
        close(fd[0]);
        dup2(fd[1], STDERR_FILENO);
        printf("%d\n", STDERR_FILENO);
        printf("%d\n", fd[1]);
        close(fd[1]);
        int st_argc = argc + 1;
        char* st_argv[st_argc + 1];
        char* st_envp[] = {"PATH=/usr/bin:/bin", NULL};
        for(int i = st_argc; i >= 2; --i) {
            st_argv[i] = argv[i - 1];
        }
        st_argv[0] = "strace";
        st_argv[1] = "-T";
        st_argv[st_argc + 1] = NULL;
        // execvp("/usr/bin/strace", st_argv);
        execve("/usr/bin/strace", st_argv, st_envp);
        dup2(origin_stderr, STDERR_FILENO);
        perror("Error: execve failed.\n");
        return 1;
    }
    // parent process

    syscall_stats stats;
    close(fd[1]);
    ssize_t n;
    char buf[MAX_LENGTH], line[MAX_LENGTH];
    n = read(fd[1], buf, sizeof(buf));
    if (n < 0) {
        perror("Error: read failed.\n");
        return 1;
    }
    int line_idx = 0;
    for(int i = 0; i < n; ++i) {
        if(buf[i] == '\n' || buf[i] == '\0') {
            line[line_idx++] = '\0';
            char* name[MAX_LENGTH];
            double time;
            getSyscallName(line, line_idx, name);
            time = getSyscallTime(line, line_idx);
            addSyscall(&stats, name, time);
            line_idx = 0;
        }
        else {
            line[line_idx++] = buf[i];
        }
    }
    return 0;
}
